adding mega_workflow
Emory-HITI/Niffler pull request #326
Opened 2022-07-27 10:07 UTC by Pavan-Bellam

2022-07-27 15:25 UTC, anbhimi approved these changes

2022-07-27 15:39 UTC, pradeeban requested changes
The whole folder hierarchy feels too redundant to me. 

Why 
modules/workflows/Nextflow_workflows/Modules/metadata_anonymization.py
instead of just
modules/workflows/metadata_anonymization.py (and all the files at this level)?

Is this mandated by NextFlow?

Please avoid unnecessary depth.

2022-07-27 15:54 UTC, pradeeban reviewed
[modules/workflows/Nextflow_workflows/Modules/metadata_anonymization.py](https://github.com/Emory-HITI/Niffler/pull/326/files#diff-dbade8098e273e7c14e7be27c0629b29ff703f920ea841efc5e7a36b0bcff75a) names feel redundant with 2 modules and 2 workflows in the folder names.

maybe, replace the "Modules" with "src"?

and flatten "workflows/Nextflow_workflows" to just "workflows" or rename it as "workflows/nf" or "workflows/nextflow"? 

You all can decide.

2022-07-28 14:58 UTC, pradeeban approved these changes

2022-07-28 14:59 UTC, merged